### ISSUE TITLE
App 通过JNI调用vsomeip接口 ,注册失败

### ISSUE THREAD

**Issue by zhongjihao** [lixiaolia/ndk-someiplib#1]
03-15 13:16:25.937 16051 16096 I         : Starting vsomeip application "vsomeip_client" (ffff) using 2 threads I/O nice 255
03-15 13:16:25.937 16051 16098 I         : shutdown thread id from application: ffff (vsomeip_client) is: 71fc7c14f0 TID: 16098
03-15 13:16:25.937 16051 16097 I         : main dispatch thread id from application: ffff (vsomeip_client) is: 71fc8bf4f0 TID: 16097
03-15 13:16:25.938 16051 16096 W         : local_client_endpoint::connect: Couldn't connect to: /storage/emulated/0/vsomeip/vsomeip-0 (No such file or directory / 2)
03-15 13:16:25.939 16051 16096 I         : io thread id from application: ffff (vsomeip_client) is: 71fc9c54f0 TID: 16096
03-15 13:16:25.939 16051 16096 I         : routing_manager_proxy::on_disconnect: Client 0xffff calling host_->on_state with DEREGISTERED
03-15 13:16:25.939 16051 16099 I         : io thread id from application: ffff (vsomeip_client) is: 71fc6c34f0 TID: 16099
03-15 13:16:25.939 16051 16097 D VSomeip_Client: on_state_cbk:169 ---zhongjihao---Application(vsomeip_client) is deregistered.

APP运行,vsomeip客户端vsomeip_client注册失败,vsomeip服务端vsomeip_server注册也失败 ,方便加个微信吗  我微信 sprdtrum

**Comment by zhongjihao** [comment]
下面是我设备下的vsomeip-local.json配置文件
IHU519G:/storage/emulated/0/vsomeip # ls
vsomeip-local.json
IHU519G:/storage/emulated/0/vsomeip # cat vsomeip-local.json                                                                                                                                               
{
    "unicast":"192.168.43.67",
    "netmask" : "255.255.255.0",
    "logging":
    {
        "level":"debug",
        "console":"true",
        "file" : { "enable" : "true", "path" : "/sdcard/vsomeip/vsomeip.log" },
        "dlt" : "true"
    },

    "applications":
    [
        {
            "name":"vsomeip_server",
            "id":"0x4444"
        },

        {
            "name":"vsomeip_client",
            "id":"0x5555"
        }
    ],

    "services":
    [
        {
            "service":"0x1234",
            "instance":"0x5678",
            "unreliable":"30509"
        }
    ],

    "routing":"vsomeip_server",
    "service-discovery":
    {
        "enable" : "true",
        "multicast" : "224.244.224.245",
        "port" : "30490",
        "protocol" : "udp",
        "initial_delay_min" : "10",
        "initial_delay_max" : "100",
        "repetitions_base_delay" : "200",
        "repetitions_max" : "3",
        "ttl" : "3",
        "cyclic_offer_delay" : "2000",
        "request_response_delay" : "1500"
    }
}

**Comment by zhongjihao** [comment]
解决

**Comment by geron-cn** [comment]
> 解决

我们遇到一样的问题了， 方便说下怎么解决的呢？ 🙏
